# Generated by Django 4.0.5 on 2022-08-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_slug_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default='0.0', max_length=10, verbose_name='Precio'),
        ),
    ]
