# Generated by Django 4.0.5 on 2022-08-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordered_date',
        ),
    ]
